### ISSUE TITLE
"flatten" function missing? (or I'm stupid, happens enough)

### ISSUE THREAD

**Issue by porkybrain** [edouarda/brigand#103]
I'm missing a function which would turn a "tree" (aka a list of lists of lists) into a list.

say I have:

    list<
        list<
            list<int>,
            bool, 
            float>,
        list<>,
        list<
            char,
            char>>

and I want:

    list<int,bool,float,char,char>

**Comment by edouarda** [comment]
Mmmm basically it would be just a replace of 

list<T...> with T...

Until it's not a T... anymore.

Sounds doable. :-)

**Comment by porkybrain** [comment]
Here is what I came up with, it probably could be done faster/less recursive though:

```C++
//if a type is a list of types it will successively be unpacked into the enclosing list
template<typename L, typename... Ts>
struct flatten_impl { using type = L; }; //default only reached with empty Ts
template<typename T>
using flatten = typename flatten_impl<list<>, T>::type;
//first of Ts is not a list
template<typename ... Ts, typename T, typename ... Us>
struct flatten_impl<list<Ts...>, T, Us...> : flatten_impl<list<Ts..., T>, Us...> {};
//frist of Ts is a list
template<typename ... Ts, typename ... Us, typename ... Vs>
struct flatten_impl<list<Ts...>, list<Us...>, Vs...> : flatten_impl<list<Ts...>, Us..., Vs...> {};
```

**Comment by edouarda** [comment]
My implementation is a bit different and more generic, you need it to work with any kind of variadic type. Also I made sure it works on VS 2013.

**Comment by porkybrain** [comment]
but now 
```C++
using l = brigand::list<list<std::vector<int>>,brigand::list<int>>;
using fl = brigand::flatten<l>;
```
becomes:
```
brigand::list<int,int,int>
```

if you were to force `Head` to be of type `L` (line 32) it should work and still be generic enough.

**Comment by edouarda** [comment]
I don't understand your remark. The current implementation doesn't work?

**Comment by porkybrain** [comment]
Yes. I understand that flatten could also mean 'unpack everything' but since its not uncommon to view a type which has template parameters as a type it would be more useful to restrict the 'tree' to us only one list type.
Surely one would not expect to get `list<char, char, char>` as the result of `flatten<list<list<std::string>>>` for example.

**Comment by edouarda** [comment]
Indeed. So we could restrict to the match of the root type only, but then...

brigand::list<boost::mpl::list<something>, char> would be not unpacked correctly.

**Comment by jfalcou** [comment]
What abotu using protect<> around ambiguous types ?

**Comment by porkybrain** [comment]
As far as my experience goes chances are very high that `something` is also going to be a template as well. 
Or from another perspective with a restricted list type I still have a workaround:
```C++
using l = brigand::list<boost::mpl::list<something>, char>;
using fl = flatten<wrap<l,boost::mpl::list>>;
```
but if we want a restricted list type and don't provide one there is no work around

**Comment by edouarda** [comment]
I thought about it and I think you are correct. Default should substitute root type only and if the user wants to replace everything he will do several pass. Will fix tonight.
