### ISSUE TITLE
Automate the generation the standalone header

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#105]
We let it slides after a bunch of commits so having a way to geenrating on every push/commit could be good.

**Comment by ccharly** [comment]
What about a custom git hook that automatically generate the standalone header (aka calling `standalone` rule of the cmake) and automatically add the file to the current commit? This is pretty trivial to do and nobody will have to take care about generation + adding it?

We can also easily add an explicit message to the commit body?

**Comment by edouarda** [comment]
Sounds awesome.

**Comment by edouarda** [comment]
Is it fine now for you @jfalcou ?
