### ISSUE TITLE
split<typename L, typename Delim> would be nice

### ISSUE THREAD

**Issue by porkybrain** [edouarda/brigand#106]
Since you guys are so quick at fulfilling feature requests how about:
```C++
split<typename L, typename Delim>
```
which would make 
```C++
using l = list<int,void,char,char,void,char,float>;
using sl = split<l,void>;
```
into 
```C++
list<list<int>,list<char,char>,list<char,float>>
```

**Comment by edouarda** [comment]
I think partition is a better name and it should accept a lambda.

**Comment by edouarda** [comment]
And I think it has been implemented for sort but will have to see if it works for that case.

**Comment by jfalcou** [comment]
partition already is a thing currently but do somethign different (produce two list depending onr esult of a predicate)

**Comment by edouarda** [comment]
Da, correct. That split thing is easy to do.

**Comment by jfalcou** [comment]
can we fast-lane it ?

**Comment by edouarda** [comment]
We can fast-lane anything if needed.

**Comment by porkybrain** [comment]
If you used a log(N) find (as suggested in #107) you should be able to do it much faster than O(n)

**Comment by edouarda** [comment]
Find isn't the problem, you still have to create the appropriate lists.

**Comment by mkurdej** [comment]
For completeness, one may want not only split<List, Delimiter>, but also split_if<List, Predicate>. The latter should be a straightforward generalisation of the former.

**Comment by edouarda** [comment]
![One does not simply split](https://imgflip.com/i/vx72d)

**Comment by ldionne** [comment]
It's not possible to split in less than O(n). Think of it; you have to create sublists with a total of n elements. That being said, big-O notation isn't worth much when talking about the complexity of metaprogramming operations, IMO.

**Comment by jfalcou** [comment]
I agree. But I think it conveys the general of idea of 'it takes this much amount o types to be instanciated'. CT is basically time to find types and to geenrate them, one beign slower than the other. Maybe some actual other metrics will be better.

**Comment by porkybrain** [comment]
I think something like this could split quickly 
```C++
template<typename T, typename U, typename V>
struct divide_impl;

template<template<typename...> class L, typename... T, typename... U, template<typename...> class L2, typename... V>
struct divide_impl<L<T...>, L<U...>, L2<V...>>
{
	template<typename... A, typename... B>
	static list<list<A...>, list<B...>> f(pair<T, A>*..., pair<U, B>*...);
	using type = decltype(f((V*)0 ...));
};
```
if you passed in two lists of different lengths of voids and the list you want to be split also packaged as a pair with the first void and the second the list type. 
Sadly it segfaults on all three major compilers but I think it is legal (im not a language lawyer though).

**Comment by porkybrain** [comment]
rather than using a pair one could use a function pointer taking the two arguments, that way the new pair type is not named and the compiler shoud be able to forget it again immediatly

**Comment by edouarda** [comment]
I think we will do it in the next milestone.
