### ISSUE TITLE
implement make_xxx

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#11]
with xxx = tuple, pair, etc

**Comment by jfalcou** [comment]
shoudl make_variant_over.hpp moved to adapt/ and we have all the other make_xx_over in there ?

**Comment by edouarda** [comment]
I think we should move it to adapt/

**Comment by jfalcou** [comment]
Currently, you don't include utility nor tuple nor variant in the adaptee but in the test so I don't think it brigns too much.
