### ISSUE TITLE
append : misbehavious

### ISSUE THREAD

**Issue by bezout** [edouarda/brigand#112]
Hi,

In the append.hpp file, if I'm not mistaken, this function line 22 :

    template<template<class...> class L, class... T>
    struct append_impl<L<T...>>
    {
      using type = L<T...>;
    };
should concatenate a list with a variadic list like this :

    template<template<class...> class L, class... T1, class... T2>
    struct append_impl<L<T1...>,T2...>
    {
      using type = L<T1...,T2...>;
    };

Tests are still ok with this change.

**Comment by edouarda** [comment]
Not sure I understand your issue, append already concatenates an arbitrary number of lists together.

**Comment by bezout** [comment]
I wanted to concatenate a list with an element.;

    append<list<A,B,C>,D>
or few elements

    append<list<A,B,C>,D,E>

without creating new lists like this

    append<list<A,B,C>,list<D,E>>

And it seems that this function 

    template<template<class...> class L, class... T>
    struct append_impl<L<T...>>
    {
      using type = L<T...>;
    };
is useless beacause it has the same input and output, so I assumed there is an issue here.

**Comment by ccharly** [comment]
This overload is needed. Assume the following example:
```c++
brigand::append<brigand::list<>, brigand::list<>>
```

This will fall under this overload (where: `T1`, `T2` and `Lr` are empty):
```c++
template<template<class...> class L1, class... T1, template<class...> class L2, class... T2, class... Lr>
struct append_impl<L1<T1...>, L2<T2...>, Lr...>
```

Which then calls this:
```c++
{
    using type = append<L1<T1..., T2...>, Lr...>;
};
```

Which is the same as:
```c++
{
    using type = append<L1<>>;
};
```

Which leads to:
```c++
template<template<class...> class L, class... T>
struct append_impl<L<T...>>
{
  using type = L<T...>;
};
```

To sum up, this overload is needed ;) I've took the example of empty lists but it is the same even if `T1` and `T2` are non empty but `Lr` is empty.

**Comment by bezout** [comment]
Ok, thanks you for the explanation :)

**Comment by edouarda** [comment]
Bezout for

```append<list<A,B,C>,D>```

Use 

```
push_back<list<A,B,C>, D>
```

**Comment by bezout** [comment]
Sure, this corresponds more to what I need.
Thank you
