### ISSUE TITLE
mpl::filter_view wannabe

### ISSUE THREAD

**Issue by didierjeanphi** [edouarda/brigand#117]
Bonsoir messieurs,

At my work, they have finally decided to move to c++11 (yeah I know...). For a small project I am working upon, I am using MPL. Last month I decided to make it more C++11 and wanted to go hana, but we are using gcc 4.7 so I'm kinda limited there...
Long story short, I discovered brigand listening to the cpp con'  youtube channel and decided to give it a try. Your work is impressive. Congratulations. 

However, I am using boost::mpl::filter_view  to select a subset from a list with a predicate. This metafunction is unfortunately not in brigand so I write one myself with the help of the examples provided. I am a newbie in the metaprogramming world and thought that I could submit my code so you guys can review and maybe make some comments or suggest a better way to emulate filter_view.

Didier 

This is my code 

```C++
 namespace extension {

	template <   class Pred,  typename elt> struct CheckPredicate;

	template <template<typename...>  class List,  template<typename...>  class Pred, typename...  Args, typename ... Ts>
	struct CheckPredicate<Pred<Args...>, List<Ts...>>
	{
	private:
	    struct fltLambda
	    {
		template<typename... Ls> struct apply { using type = typename  Pred<Ls...>::type::type; /*should be of type integral_constant*/ };
	    };
	    using lambda = brigand::apply < brigand::bind < fltLambda, Args... >, Ts... > ;
	public:
		static constexpr typename lambda::value_type value = lambda::value;
	};
}// !extension
  
//------------------------------------------------------
template <typename... Ts> using  list = brigand::list<Ts...>;


template <typename... Lists> struct listbuilber;
template <> struct listbuilber<> { using type = list<>; };
template <typename... Ts> struct listbuilber<list<Ts...>> { using type = list<Ts...>; };
template <typename... Ts, typename... Us> struct listbuilber<list<Ts...>, list<Us...>> { using type = list<Ts..., Us...>; };
template<typename... Ts, typename... Us, typename... Rest> struct listbuilber<list<Ts...>, list<Us...>, Rest...> { using type = typename listbuilber<list<Ts..., Us...>, Rest...>::type; };


template <typename Pre, typename... Ls> struct filter_helper;

template <template<typename...> class Pred,typename T,  typename... Args>
struct filter_helper<Pred<Args...>, T> 
{
	//if C++14 :
	// using type = typename std::conditional_t <  extension::CheckPredicate< Pred<Args...>, list< T> >::lambda::value, list<T>, list<>>;
   using type = typename std::conditional <  extension::CheckPredicate< Pred<Args...>, list< T> >::value, list<T>, list<>>::type;
};
template <typename Pre, typename List>
using filter_impl =typename filter_helper<Pre, List>::type;

template < typename Ls, typename Pre> struct filter_seq;

template <template <typename...> class Pred, typename... Args, typename... Ts> 
struct filter_seq < brigand::list<Ts...> ,  Pred<Args...> >
{
	using type = typename listbuilber< filter_impl< Pred<Args...>, Ts>...>::type;
};

```

test 

```C++

namespace AssertTest
{
  
      class A {};
      class B {};
      class C {};
      class D {};

      using set_test = brigand::set< float,  A , char, B, C,  int,D >;
      using isetClass =  brigand::filter::filter_seq < brigand::as_list < set_test >,  std::is_class< brigand::_1>  >::type;
      // return a subset containing only the elements of set_test satisfying the predicate
      static_assert ( brigand::size<isetClass>::value == 4, " no classes in this list"  );
      static_assert ( std::is_same < brigand::at_c<isetClass, 0> , A>::value ," elt 0 is not of type A "  );
  
}
	

```

**Comment by porkybrain** [comment]
Sorry for my lack of knowledge of the boost MPL but what is the difference between a filter_view and the result of a remove_if?

**Comment by didierjeanphi** [comment]
@PorkyBrain 
In file :

http://www.boost.org/doc/libs/1_59_0/boost/fusion/algorithm/transformation/remove_if.hpp

remove_if calls filter_view. Brigand has remove_if and sure I could have used it. I could have also implement my filter using brigand::remove_if but the rationale behind my implementation is also educational (remember that I'm a newbie).

**Comment by edouarda** [comment]
Hi Didier, glad you're giving brigand a spin. Although Brigand is a Boost.MPL replacement it doesn't mean you have a 1:1 mapping of functions. In your case remove_if is a simpler solution.

**Comment by didierjeanphi** [comment]
Hi Edouard,
This is what I ended up doing, using remove_if...It has a big advantage that I just have to include the standalone hpp. My trying to write a filter has helped me a great deal to understand the internals of your lib.
