### ISSUE TITLE
Implement brigand::index_of

### ISSUE THREAD

**Issue by mkurdej** [edouarda/brigand#121]
It would be nice to have `index_of` and not only `find` in some cases (and to avoid creating maps of type `{0: type0, 1: type1, ...}`.

FYI, my case is to index a run-time sequence using compile-time indices from `brigand:list`.

**Comment by edouarda** [comment]
index_of is the size of the part of the sequence you eliminate... or size of total sequence minus size of remaining sequence, but the helper function could be useful, agreed

**Comment by edouarda** [comment]
Looks good but now it conflicts

**Comment by mkurdej** [comment]
I've fixed the conflicts.
