### ISSUE TITLE
make_sequence has max instantiation depth issues 

### ISSUE THREAD

**Issue by jonathanpoelen** [edouarda/brigand#132]
`make_sequence<size_t<0>, 999>` exceeds maximum depth with a error `struct brigand::next<brigand::next< ... < std::integral_constant<long int, 0l> ... > >`.

`next` is a class:
```
  template <typename A>
  struct next : std::integral_constant < typename A::value_type, A::value + 1 > {};
```

Implementation of `make_sequence`:
```cpp
  template<class Start, unsigned N, template<class> class Next, template<class...> class List, class... E>
  struct make_sequence_impl<Start, N, Next, List<E...>, true>
  {
    using t1 = Next<Start>;
    using t2 = Next<t1>;
    using t3 = Next<t2>;
    .....
  };
```

Here, `t3` = `next<next<next<Start>>>` instead of `std::integral_constant<T, Start+3>` because `next` is not an alias. One reason for this?

**Comment by jonathanpoelen** [comment]
I think `make_sequence` should use `apply` for `next`. Therefore, the `template<class> class Next = next` parameter becomes `class Next = quote<next>`.

What do you think ?

**Comment by porkybrain** [comment]
good idea! I'll benchmark it Monday

**Comment by edouarda** [comment]
I agree, it's a good idea.

**Comment by jonathanpoelen** [comment]
Je suis confus, je n'arrive pas à reproduire l'erreur sur la récursivité. Je pense avoir laissé un `-ftemplate-depth=13` dans ma ligne de compilation :/.

Sinon, utiliser `apply` rend make_sequence ~3x plus lent. Avec une optimisation de `quote`, cela descend à 2x.
De plus, parce que `apply` dépend de `at_c` qui dépend de `make_sequence`, j'ai ajouté une nouvelle list: `filled_list`. Celle-ci est extrêmement rapide à construire. Pour 16383 éléments:
- gcc: 0.21s/45M
- clang: 0.38s/83M

Je pense appliquer le même procédé à `range`/`reverse_range`.


I'm confused, I can not reproduce the error on recursion. I think I left a `13` -ftemplate-depth = in my line of compilation: /.

Otherwise, use `apply` makes make_sequence ~ 3x slower. With optimized `quote`, it comes down to 2x.
Also, because `` apply` depends at_c` dependent make_sequence` `I have added a new list:` filled_list`. This is extremely fast to build. To 16383 elements:
- Gcc: 0.21s / 45M
- Clang: 0.38s / 83M

I think applying the same process to range` `/` reverse_range`.
