### ISSUE TITLE
pop_front_n and pop_back_n

### ISSUE THREAD

**Issue by jonathanpoelen** [edouarda/brigand#133]
- [x] `pop_front_n<L, I>`
- [x] `pop_back_n<L, I>`
- [x] `pop_front_n_c<L, int>`
- [x] `pop_back_n_c<L, int>`

# Example

`pop_front_n_c<list<_1, _2, _3, _4, _5>, 3> = list<_4, _5>`
`pop_front_n_c<list<_1, _2, _3, _4, _5>, 30> = list<>`

# Note
`detail::without_last_element` is a kind of `pop_back_n`.

**Comment by edouarda** [comment]
Not a big fan of the name pop_front_n. Can't we do better?

**Comment by jonathanpoelen** [comment]
- pop_front/pop_back with a second parameter: `pop_font<l, n = size_t<1>>`.
- `slice<l, start, stop>` with `pop_front_n<l, n>` => `slice<l, n, ~0ull>` and `pop_back_n<l, n>` => `slice<l, 0, -n>`.
- `splice<l, start, delete_count, inserted...>` with `pop_front_n<l, n>` => `splice<l, n, ~0ull>` and `pop_back_n<l, n>` => `splice<l, 0, -n>`.
- `split_at<l, n>`::first / second

**Comment by edouarda** [comment]
Yes I think it's better and less confusing.

**Comment by jonathanpoelen** [comment]
- Blue or red ?
- Yes

... O_o

I guess the first proposal: optional size parameter for pop_front and pop_back?

What becomes pop_back_n_c <L, uint>? Renamed or removed? ~~Yes~~ ;)

**Comment by edouarda** [comment]
You need to roll a D20 and add your intelligence and charisma score. If the results is not Pi, then you will need to roll 3 D6 and substract your TMP score. Also, your character dies and all your belongings will be sold on ebay for $1.

**Comment by edouarda** [comment]
I think we might need to take pop_back_n_c to the pet doctor for its ultimate trip.

```cpp
pop_font<l, n = size_t<1>>
```

Looks groovy.

**Comment by jonathanpoelen** [comment]
What if N is greater than the number of element? I thought to make a `min(size<L>, N)` if N is specified. Otherwise, it can also make a compilation error.

**Comment by porkybrain** [comment]
I would rather get a compilation error

**Comment by edouarda** [comment]
Agreed on the compilation error.
