### ISSUE TITLE
Implement split_at

### ISSUE THREAD

**Issue by porkybrain** [edouarda/brigand#139]
since joining seems to be quite fast this opens up other opportunities when making other algorithms faster. For example reverse_find currently takes about as long as 30 remove_if on the same list. If we were to alternatively do a 

```C++
brigand::back<brigand::wrap<brigand::transform<
                      in_list, brigand::make_sequence<brigand::size_t<0>,
                      brigand::size<L>::value>,
                      pred_returning_empty_list_or_index>,
                  brigand::append>>;
```
we would have the index of the last found object much faster. If we had a split_at that was fast or a fast drop in this case we could still probably be much better than the current implementation. 
Implementing normal split in terms of split at would also yield a speed up.

**Comment by edouarda** [comment]
What would split_at do? I think we already have functions that do what you want.

**Comment by porkybrain** [comment]
I pass in a list and an index and it returns a list up to that index and a second list with the rest.

**Comment by edouarda** [comment]
That's what find does, if I'm not mistaken. I coded it with 9 hours of jetlag. Ah! The mirth.

**Comment by porkybrain** [comment]
Doesn't find just give you the rest of the list but not the elements up to that point? Besides find matches things not indexes.

**Comment by edouarda** [comment]
I see that we have split by criteria but not by index.
