### ISSUE TITLE
brigand find, find_if, reverse_find, reverse_find_if

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#14]

**Comment by jfalcou** [comment]
4a35f8c73bbc3168901ad834ca72be2918243330 Implement find and find_if with an unique API.
reverse_find probably need we have a reverse algorithm first ?

**Comment by edouarda** [comment]
Yes I think it is better to do using reverse_find = find(reverse)

**Comment by jfalcou** [comment]
reverse_find = reverse(find(reverse)) actually

**Comment by edouarda** [comment]
Reverse is there, you know what to do. :)

**Comment by jfalcou** [comment]
reverse_find done in 76aea2fadbccc6ee71fa8468a72202918d427c02
