### ISSUE TITLE
Implement count_if

### ISSUE THREAD

**Issue by porkybrain** [edouarda/brigand#140]
although brigand::found and brigand::not_found cover the "is there none?" and "is there any?" cases the "how many are there?" case is currently covered by a `brigand::size<brigand::remove_if<input, brigand::not_<pred>>>` which may not be intuitive to the user.

**Comment by ldionne** [comment]
Tip for `count_if`:

```c++
template <typename Pred, typename ...T>
struct count_if {
    static constexpr std::size_t count_impl() {
        std::size_t result = 0;
        int expand[] = {(Pred::template apply<T>::value ? ++result : 0)...};
        return result;
    }  

    using type = std::integral_constant<std::size_t, count_impl()>;
};
```

Maybe that works on MSVC, maybe it doesn't.

**Comment by porkybrain** [comment]
Looks good but its not c++11 and no chance on msvc12. But maybe its time to start ifdefing ;)

**Comment by jonathanpoelen** [comment]
``` c++
template<int, bool> struct count_accu_item {};
template<int i> struct count_accu_item<i, true> { char dummy; };

template<class Ints, bool... Vs>
struct count_accu;

template<int... I, bool... Vs>
struct count_accu<brigand::list<std::integral_constant<int, I>...>, Vs...>
: count_accu_item<I, Vs>...
{};

template<class L, class Pred>
struct count_if;

template<template<class...> class L, class... T, class Pred>
struct count_if<L<T...>, Pred>
: std::integral_constant<std::size_t, sizeof(count_accu<
  brigand::range<int, 0, sizeof...(T)>,
  bool(brigand::apply<Pred, T>::value)...
>)>
{};

template<template<class...> class L, class T, class Pred>
struct count_if<L<T>, Pred>
: std::integral_constant<std::size_t, bool(brigand::apply<Pred, T>::value)>
{};

template<template<class...> class L, class Pred>
struct count_if<L<>, Pred>
: std::integral_constant<std::size_t, 0>
{};
```

**Comment by jfalcou** [comment]
@porkybrain  i start wondering about ifdef'ing too.

**Comment by mjcaisse** [comment]
Is brigand targeted at C++11 or for specific releases of compilers? We are having similar discussions about other libraries. As you know, ifdef'ing creates headaches for maintenance and testing but it might increase your user base.

**Comment by jfalcou** [comment]
@mjcaisse we try to support at least MSVC2013 Update 4. That's basically our only downward limit.

**Comment by porkybrain** [comment]
I opened #146 as a related issue. I think that we should be wary of implementing one algorithm per compiler but a two tier approach, one done right and one broken compiler version would probably widen our user base.

**Comment by porkybrain** [comment]
@jonathanpoelen sorry for not commenting sooner, your impl looks good.

**Comment by jonathanpoelen** [comment]
If you made a bench, please, use brigand::range from pull request #144.

**Comment by edouarda** [comment]
It's now in master.
