### ISSUE TITLE
FYI: Working on a framework for doing compile-time benchmarks

### ISSUE THREAD

**Issue by ldionne** [edouarda/brigand#143]
This is not really an issue, but I wanted to post this here since it's a good way to reach a few metaprogrammers. I've started extracting Hana's benchmark framework into its own CMake module called [Metabench](https://github.com/ldionne/metabench). I know you guys were looking for ways of doing compile-time benchmarks, so you might be interested to have a look. It's really a work in progress, but I'd like to turn this into a joint effort between metaprogrammers. I think we all need a decent framework for compile-time benchmarks.

**Comment by porkybrain** [comment]
Awesome! 

I guess if your going to have to learn some despicable language like ruby it should at least be the god of metaprogramming that forces you to do it ;)

**Comment by ldionne** [comment]
Would you prefer Python? Is there a good template engine for Python?

**Comment by porkybrain** [comment]
Personally yes, python is very much my preference , i am no expert but i understand the xpcc Library authors have had extensive experience with c++ and python Template engines. @salkinum @ekiwi care to comment?

**Comment by porkybrain** [comment]
@salkinium

**Comment by salkinium** [comment]
Who dares to wake me from my slumber?! ;-P

xpcc uses the [Jinja2 template engine](http://jinja.pocoo.org) integrated into SCons with a lot of custom code.

A more standalone version of this concept that can be called from CMake, is being integrated by me into [mbed OS here](https://github.com/ARMmbed/target-mbed/pulls). Some of the code there is mbed OS specific (mostly where the data for the templates comes from).

I strongly recommend using something more advanced than the C preprocessor for code generation.
Also note, that Ruby has a [template engine called Liquid](http://liquidmarkup.org), which uses very similar if not identical template syntax to Jinja2.

**Comment by ldionne** [comment]
Ok; the thing is already written with Ruby and ERB templates, and I have a large number of benchmarks in Hana already written that way. And I don't mind Ruby, so I would be crazy to change it myself. That being said, if someone comes up with an equivalent implementation in Python that's just as easy to use as the current one, then I'll consider switching to it because I know Python is more popular in the C++ community. Anyway, I'll close this cause my goal is not to hijack Brigand's issue system.

**Comment by porkybrain** [comment]
Saying @salkinium wakes you from slumber? I need to write a bot. 

C preprocessor is off the table any way since we are benchmarking compile time efficientcy. Putting your feet to the fire: would you suggest using your CMake + Jinja2 to benchmark template metaprogramming libraries like boost.Hana or brigand? I understand @ldionne already has a working setup within hana and you being probably the most knowledgable guy i know on the subject if you can't suggest a python solution then i probably should shut up and learn Ruby.

**Comment by porkybrain** [comment]
lol synchronous posting.

**Comment by salkinium** [comment]
:+1: for not rewriting working code.
