### ISSUE TITLE
Brigand works with exceptions turned off, will it stay that way?

### ISSUE THREAD

**Issue by porkybrain** [edouarda/brigand#148]
Supporting MSVC12 essentially bans all generalized constexpr use which elides the problem of constexpr functions that assert by throwing and designs which turn off exceptions. However as we have been talking about making compiler specific versions of algorithms of late it begs the questions if we will maintain this no exception policy into the future?

Since we are still taking all arguements as template parameters and would only be using constexpr in algorithm implementations we could propagate the error in the form of an invalid return value and then static assert as soon as we are back in template context. Alternatively this workaround also seems to work http://stackoverflow.com/questions/35186327/how-do-i-assert-from-constexpr-function-with-exceptions-disabled/.

As far as I know its not just us small processor embedded guys who must turn off exceptions, gamedevs and google do it all the time too.

**Comment by edouarda** [comment]
We can decide to not use constexpr for that reason. Let's not over-engineer...

**Comment by porkybrain** [comment]
Maybe completely banning constexpr is overkill. My request would be to ban throwing.

**Comment by edouarda** [comment]
No need to take a decision now, so why take it? :-)
