### ISSUE TITLE
implement erase with map

### ISSUE THREAD

**Issue by jonathanpoelen** [edouarda/brigand#164]

**Comment by edouarda** [comment]
We thought about it, one way would be to have a facade for the map that marks the deleted entries as not there.

**Comment by jfalcou** [comment]
not sure we still want to go through facade stuff. Not before the resolution of #96

**Comment by edouarda** [comment]
I agree.

**Comment by edouarda** [comment]
What's the situation on this feature now?

**Comment by jonathanpoelen** [comment]
Still missing... like for has_key.
I do it.

**Comment by edouarda** [comment]
Thanks!
