### ISSUE TITLE
Improve compiler detection macros

### ISSUE THREAD

**Issue by edouarda** [edouarda/brigand#168]
We provided users with a basic tool to detect compilers, in the next version it would be great to give access to the compiler version as well.

**Comment by porkybrain** [comment]
clang on visual studios defines _MSVC_VER which leads to misdetection.

**Comment by edouarda** [comment]
That's correct, so we need to check for cland AND msvc

**Comment by edouarda** [comment]
This should work:

```cpp
#if  define(_MSC_VER) && !defined(__clang__)
#define BRIGAND_COMP_MSVC
#endif
```

Do you know if gcc does the same?

**Comment by porkybrain** [comment]
I can check, we use visual gdb at work
