### ISSUE TITLE
reverse_range API is error-prone

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#170]
MSVC 2015 U2 and MinGW g++ 5.1 seems affected

**Comment by jfalcou** [comment]
FYI, calling reverse on range does not exhibit the issue.

**Comment by edouarda** [comment]
What's the bug exactly, you do range on which kind of collection?

**Comment by jfalcou** [comment]
Nah, I'm stupid. reverse_range also reverse its input (reverse_range<10,0>) and I was calling reverse_range<0,10>. Maybe we shoudl fix this API issue.

**Comment by jonathanpoelen** [comment]
I thought the same thing last night :)

**Comment by edouarda** [comment]
Indeed, we should, it's an easy fix.

**Comment by edouarda** [comment]
I'm not sure it's error prone, because I think it's easier to understand that

```cpp
reverse_range<int, 10, 5> gives "10, 9, 8, 7, 6"
```

than

```cpp
reverse_range<int, 5, 10> gives "10, 9, 8, 7, 6"
```

**Comment by jfalcou** [comment]
Then can't we shove the current impl in detail:: and have range<T,A,B> checks if A > B to select the implementation so `range<int,10,5>` and `range<int,5,10>` do what we think ?

**Comment by edouarda** [comment]
It's easy to do, but I think it's confusing. Maybe a static assert to prevent mixing the inputs?

**Comment by edouarda** [comment]
@jfalcou if you are ok with it I will close the issue.

**Comment by porkybrain** [comment]
I like x down to y notation and I think a static_assert should be enough.

**Comment by jfalcou** [comment]
static_assert and be done with it. I don't think this needs to be SFINAE friendly.

**Comment by edouarda** [comment]
Fine by me, I will do that today.
