### ISSUE TITLE
is_set: the results differ between compilers (clang/gcc vs msvc)

### ISSUE THREAD

**Issue by jonathanpoelen** [edouarda/brigand#175]
`brigand::is_set<void, int&, int, int>::value` = false with clang and gcc, true with msvc.

**Comment by mkurdej** [comment]
MSVC 2015 (at least Update 2) is correct about it.
MSVC 2013 (Update 5, MSVC 18.0.40629.0) fails.

Maybe minimum MSVC version should be changed?

**Comment by edouarda** [comment]
блин We no longer work on MSVC 2013? We have on the roadmap to remove VS2013 support but I'd like to wait for the next VS.

**Comment by edouarda** [comment]
With the detection of MSVC versions, we can add this:

```cpp
#pragma message("brigand::is_set is known to return false positives with MSVC 2013")
```
