### ISSUE TITLE
possible performance enhancement of at

### ISSUE THREAD

**Issue by porkybrain** [edouarda/brigand#189]
have we tested a form of at which uses std::declval() to call `at()` and a "universaly convertable struct" to swallow the values?

```C++
struct everything_converts_to_me{ 
    template<typename T>
    everything_converts_to_me(T&&){}
};
```

**Comment by ldionne** [comment]
This was the original idea by Richard Smith. I remember benchmarking it at some point and it was much slower than the `void*` trick, which is why I started using it.

**Comment by porkybrain** [comment]
It seems to actually be declval that is so slow, I would not have expected that.

**Comment by brunocodutra** [comment]
Just a heads up, it seems pointers are much easier to handle than references, to the point a handcrafted `declptr` actually performs much better than  `declval` on Clang and GCC.

BTW I've struggled with ICEs and otherwise non conforming behaviour on GCC when using both lvalue and specially rvalue references in SFINAE contexts.

**Comment by porkybrain** [comment]
I just thought of another way to do at, something like this:
```C++
namespace detail
{
	template<std::size_t N, typename Indexes, typename Seq> struct at_impl;
	template<std::size_t N, std::size_t...Is, template<typename...> class L, class... Ts>
	struct at_impl<N, std::integer_sequence<std::size_t,Is...>, L<Ts...>> : 
		std::enable_if<(N == Is),Ts>... //note: not using enable_if as origionally intended
	{}; 
}

template <class L, std::size_t Index>
using at_c = typename detail::at_impl<Index, std::make_index_sequence<brigand::wrap<L,brigand::count>::value>, L>::type;
```
It seems to be pretty much exactly the same speed on clang for huge lists. Anyone have any ideas how to tweak it further?

**Comment by porkybrain** [comment]
looking at the implementation in type_traits it looks like `make_index_sequence` could be fast tracked. I wonder why it is not a compiler intrinsic.

**Comment by porkybrain** [comment]
on GCC the difference is bigger, fast tracking make_index_sequence helps but this is still slower. Testing on even bigger lists on clang show that this is also slower there but only by like 5%.

**Comment by brunocodutra** [comment]
Doesn't it break if the list happens to contain multiple identical elements?

**Comment by brunocodutra** [comment]
Have you considered the classical [multiple-inheritance-deduction-trick](https://github.com/brunocodutra/metal/blob/bare/include/metal/detail/lookup.hpp)?

Also notice Louis' addition to Clang adding the intrinsic `__type_pack_element` has just recently been merged to trunk. See [here](https://github.com/brunocodutra/metal/blob/builtin_at/include/metal/list/at.hpp) for an example of how to implement `at` using it.

> I wonder why it is not a compiler intrinsic.

It is on `libc++`, but you can use Clang's intrinsic `__make_integer_seq` directly anyways.

**Comment by porkybrain** [comment]
multiple equal indexes are impossible, its a sequence. However your point is correct that at will surely eventually be intrinsic in all major compilers

**Comment by brunocodutra** [comment]
I don't mean equal indices, but equal values really. Notice multiple copies
of std::enable_if<false, value> would be inherted, or am I overlooking
anything?

**Comment by porkybrain** [comment]
ah no I am overlooking the problem, I started with a special struct and then just thought "I can just use enable if" but that change is fatal, you are correct. You can however build your own enable if which also takes the indicie as a parameter and is specialized on index and indicie being equal. Then there are no ambiguities.

**Comment by brunocodutra** [comment]
Indeed. I remember testing this alternative in the past and it was slower
than the multiple inheritance deduction I ended up favouring, but maybe it
was just my poor implementation of the idea.

**Comment by porkybrain** [comment]
any way I think at is about as good as I can come up with now so closing this again
