### ISSUE TITLE
template_count_bools use raw constexpr

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#198]
Which makes cl.exe 18.00.40629 for x86 not compiling. 
Can we have a conditionnal compile here to use old version for MSVC2013 ?

**Comment by edouarda** [comment]
I need to update the macros.

**Comment by porkybrain** [comment]
We could just make the MSVC version work with 13. This seems inconsistent with our plan of deprecating msvc13 though. When I have time I would like to go through and separate out the cases where msvc15 support is holding us up and make two versions, one fast and one Microsoft.

**Comment by jfalcou** [comment]
I still got a lot of 2013 users and a lot of the new code breaks because of this. I also have issues with range and there, the fix is to call the detail impl :/ 

I think it's still a bit early to toss 2013. It means missed sales for us.

**Comment by jfalcou** [comment]
didn't we had a MSVC2013 bot anyway ?

**Comment by edouarda** [comment]
I believe we have, do you have the right update?

**Comment by jfalcou** [comment]
I have cl.exe 18.00.40629

**Comment by porkybrain** [comment]
Ok fine by me. Provided we have good macros I can't think of anywhere specific where we cannot support MSVC13, it will probably slow down MSVC15 though because I pretty sure no one wants to make 3 versions ;)

**Comment by jfalcou** [comment]
after a bunch of test, the only quirks are : 

 - this wild constexpr
 - the fact that, in some context, I can't use the eager range<> I need to go through range_impl<>::type

**Comment by edouarda** [comment]
I will add a macro for MSVC2013 and 2015.

**Comment by jfalcou** [comment]
What was our stance on lazy//eager ? Could we have a lazy::range<T,N,M>::type so I don't delve into detail:: ?

**Comment by edouarda** [comment]
By default we are eager and if you want lazy you need to do use the lazy namespace.

See fold: https://github.com/edouarda/brigand/blob/master/brigand/algorithms/fold.hpp

**Comment by jfalcou** [comment]
Yeah, but I think range don't support this.

**Comment by edouarda** [comment]
Yes, we didn't do the distinction for range.

**Comment by edouarda** [comment]
I've updated the macros so that you can distinguish VS2013 and VS2015.

**Comment by edouarda** [comment]
Shall I close this issue?

**Comment by jfalcou** [comment]
It's merged so yes
