### ISSUE TITLE
basic doc changes after universal lambda merge

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#201]
Is there any part of the doc that should be changed w:r to the fact _1 and the way we define/use lmabda changed with latest merges ?

**Comment by porkybrain** [comment]
The references to "quote" in the algorithm tutorial are outdated

**Comment by edouarda** [comment]
Can you update it?

**Comment by edouarda** [comment]
I'm still looking for tutorials ideas by the way, see #15

**Comment by porkybrain** [comment]
Yes I will add some stuff to the docs

**Comment by edouarda** [comment]
Thanks a lot!

**Comment by porkybrain** [comment]
I threw out or rewrote everything that was wrong. If I find time I will write more examples and stuff.

**Comment by edouarda** [comment]
I'll review it tonight.

**Comment by edouarda** [comment]
Looks good!
