### ISSUE TITLE
a fast take is possible

### ISSUE THREAD

**Issue by odinthenerd** [edouarda/brigand#211]
For divide and conquer algorithms we need a fast `drop` and a fast `take`. Where we know how to do a fast `drop` the speed of `take` is currently a huge bottleneck on big lists. Talking to my new intern @chieltbest about compiler remembering point of instantiation and memoization it occurred to me that using nested aliases we could make much better use of memoization where we need it and avoiding it where we don't. 

Essentially the problem with recursive metafunctions is the intermediate types which need to be generated. Recursive aliases do not create intermediary types, on the other hand they can't make decision either and therefor can't terminate. Aliases also can't unpack lists so you also essentially only have one variadic pack at your disposal. If we separate the "algorithm" part from the "data" part by traversing through a kind of "meta state machine" with a "meta monad", selecting the next alias based on abstract data from the running recursion depth count, we can rely on memoization to remember the abstract steps and allow the compiler to forget the other intermediate steps of working on data because that is all in aliases. 

Here is an example of using this pattern to make a faster `take` algorithm:

``` cpp

constexpr int rot_sm(const int i) {
    return i == 0 ? 0 : i < 8 ? 1 : i<16 ? 2 : i<64 ? 3 : 4;
}

template<int I>
struct rot_generator {
    template<int I, class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7,
        class T8, class T9, class T10, class T11, class T12, class T13, class T14, class T15,
        class T16, class T17, class T18, class T19, class T20, class T21, class T22, class T23,
        class T24, class T25, class T26, class T27, class T28, class T29, class T30, class T31,
        class T32, class T33, class T34, class T35, class T36, class T37, class T38, class T39,
        class T40, class T41, class T42, class T43, class T44, class T45, class T46, class T47,
        class T48, class T49, class T50, class T51, class T52, class T53, class T54, class T55,
        class T56, class T57, class T58, class T59, class T60, class T61, class T62, class T63, typename...Ts>
        using invoke = typename rot_generator<rot_sm(I - 64)>::template invoke<I - 64, Ts..., T0,  T1,  T2,  T3,  T4,  T5,  T6,  T7,
         T8,  T9,  T10,  T11,  T12,  T13,  T14,  T15,
         T16,  T17,  T18,  T19,  T20,  T21,  T22,  T23,
         T24,  T25,  T26,  T27,  T28,  T29,  T30,  T31,
         T32,  T33,  T34,  T35,  T36,  T37,  T38,  T39,
         T40,  T41,  T42,  T43,  T44,  T45,  T46,  T47,
         T48,  T49,  T50,  T51,  T52,  T53,  T54,  T55,
         T56,  T57,  T58,  T59,  T60,  T61,  T62,  T63>;
};

template<>
struct rot_generator<3> {
    template<int I, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename...Ts>
    using invoke = typename rot_generator<rot_sm(I - 16)>::template invoke<I - 16, Ts..., T0, T1, T2, T3, T4, T5, T6, T7,
        T8, T9, T10, T11, T12, T13, T14, T15>;
};


template<>
struct rot_generator<2> {
    template<int I, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename...Ts>
    using invoke = typename rot_generator<rot_sm(I - 8)>::template invoke<I - 8, Ts..., T0, T1, T2, T3, T4, T5, T6, T7>;
};

template<>
struct rot_generator<1> {
    template<int I, typename T, typename...Ts>
    using invoke = typename rot_generator<rot_sm(I - 1)>::template invoke<I - 1, Ts..., T>;
};

template<>
struct rot_generator<0> {
    template<int I, typename T, typename...Ts>
    using invoke = list<T,Ts...>;
};

template<typename L, int I>
struct rotate_impl;
template<typename T, typename...Ts, int I>
struct rotate_impl<list<T, Ts...>, I> {
    using type = typename rot_generator<rot_sm(I)>::template invoke<I, T, Ts...>;
};

template<typename L, int I>
using rotate = typename rotate_impl<L, I>::type;

template<typename L, int I>
using take = meta::drop<rotate<L, I>, i<brigand::size<L>::value - I>>;

//comparing to metal's equivalent
template<typename L, int I>
using metal_take = metal::range<L,metal::number<0>,metal::number<I>>;
```

Since we only have one variadic pack at our disposal in quasi recursive aliases we cannot move stuff from list to another but we can rotate it by taking from the front and adding it to the back. Therefore for `take<L,N>` we only need to rotate `L` by `N` and then drop `size<L>::value - N` and we are left with a list of elements 0..N. 

On my machine with clang 3.7 doing 10 takes of random lengths of 10 distinct lists of 500 elements I get almost 10x better performance with the new `take`. The kicker is that `rot_generator<x>` can be memoized by the compiler regardless of the parameters passed to its respective `invoke`. 

I would expect all non `transform` based algorithms to benefit from this pattern which I am calling "meta monad" (I am very open to a better name). For example I was able to beat brigands current `at` implementation which hint's that we may even be able to beat the current `drop` algorithm using this quasi recusing alias pattern.

**Comment by porkybrain** [comment]
I can confirm that drop using this method is like 2x faster than `meta::drop`.

**Comment by brunocodutra** [comment]
Mind benchmarking metal::drop against yours for me?

**Comment by brunocodutra** [comment]
... and metal::take

**Comment by porkybrain** [comment]
take:
metal 25.5s
this 2.39s

drop:
metal 3.97s
this 0.75s

**Comment by brunocodutra** [comment]
Thanks!

**Comment by porkybrain** [comment]
even replacing `typename std::conditional<F<Ts>::type::value, NewType, Ts>::type` with 

```cpp
	template<bool>
	struct cond_alias;
	template<>
	struct cond_alias<true> {
		template<typename T, typename U>
		using invoke = T;
	};
	template<>
	struct cond_alias<false> {
		template<typename T, typename U>
		using invoke = U;
	};

    //use case
    typename cond_alias<F<Ts>::value>::template invoke<NewType, Ts>
```
is a noticeable performance boost.

**Comment by edouarda** [comment]
On all compilers?

**Comment by porkybrain** [comment]
on clang it is, on MSVC it probably will not work at all. @chieltbest can you benchmark on GCC?

**Comment by chieltbest** [comment]
alright, here are the different results for both gcc and clang:
- clang
  - new cond: 0.1072s
  - old cond: 0.1508s

- gcc
  - new cond: 1.63s
  - old cond: 2.23s

for reference, i used the following function to do the benchmarks:
```c++
template<unsigned int n>
struct count : cond<n == 0, const_int<int, 0>, count<n - 1>>::r {};

int i = count<2048>::value;

int main() {}
```

**Comment by odinthenerd** [comment]
this thread of thought has gone on in my blog and meeting C++ lightning talk, we can close it here.
