### ISSUE TITLE
Creating a list without duplicates from other list.

### ISSUE THREAD

**Issue by CvRXX** [edouarda/brigand#226]
Hello,

I'm wondering how I could do the following with brigand:

We have a list A which contains types which have subtypes: 

`using A = brigand::list<T1<ST1>,T2<ST1>,T3<ST2>,T4<S2>,T5<ST3>>`
for example T1 looks like this:
``` cpp
template<SubType>
struct T1{
  using ST = SubType;
}
```

I would like to make from this list a list of subtypes without duplicates. So it would look like this:

`brigand::list<ST1, ST2, ST3>`

How do I achieve such a thing with brigand. Thanks in advantage!

BTW: This is an epic library, keep up the good work!

**Comment by edouarda** [comment]
Would creating a set solve your problem?

**Comment by CvRXX** [comment]
But how do I get the sub types from the other list in?

**Comment by edouarda** [comment]
You write a functor with a copy algorithm?

**Comment by CvRXX** [comment]
oke, will try that

**Comment by CvRXX** [comment]
Ah oké, but how do I get the sub types in there then? 

On 22 December 2016 10:38:39 CET, "Edouard A." <notifications@github.com> wrote:
>Would creating a set solve your problem?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/edouarda/brigand/issues/226#issuecomment-268759039

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by odinthenerd** [comment]
The way join is implemented it should unwrap the types for you

----- Ursprüngliche Nachricht -----
Von: "Carlos van Rooijen" <notifications@github.com>
Gesendet: ‎22.‎12.‎2016 21:01
An: "edouarda/brigand" <brigand@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: Re: [edouarda/brigand] Creating a list without duplicates from otherlist. (#226)

Ah oké, but how do I get the sub types in there then? 

On 22 December 2016 10:38:39 CET, "Edouard A." <notifications@github.com> wrote:
>Would creating a set solve your problem?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/edouarda/brigand/issues/226#issuecomment-268759039

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
