### ISSUE TITLE
Transitioning from Brigand to mpl2 for Boost proposal

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#233]
make it a branch here OR should we make a separate repo ?

**Comment by edouarda** [comment]
Both have pros and cons.

**Comment by edouarda** [comment]
We can start with a branch?

**Comment by CvRXX** [comment]
I think making a new repo would be better because many people depend on the old brigand.

**Comment by edouarda** [comment]
Thanks for your input, we're going to do a migration.
