### ISSUE TITLE
Invalid brigand/brigand.hpp

### ISSUE THREAD

**Issue by Jarod42** [edouarda/brigand#24]
`#include` are invalid:

- *s* are missing for most directory (`#include <brigand/algorithm/apply.hpp>` should be `#include <brigand/algorithms/apply.hpp>`...)
- some files are misplaced: `size.hpp` is in `sequences`, not `algorithm`.

As there is no forward declaration for `boost::variant`, `boost/variant` is required before include `brigand.hpp` :(.

**Comment by edouarda** [comment]
Size is a helper which is Sequence specific, which is why it is in sequences. Being in sequences helps understand exactly what it is about: "the size of a sequence". If it were in algorithms I'm afraid its purpose would be confusing.

I will add the forward declaration and fix the includes as well.
