### ISSUE TITLE
I think you broke Metabench

### ISSUE THREAD

**Issue by ldionne** [edouarda/brigand#243]
https://travis-ci.org/ldionne/metabench/jobs/212628064#L1359

Please have a look and let me know.

**Comment by mkurdej** [comment]
It must be the commit https://github.com/edouarda/brigand/commit/91d4ff1487d9f1d10f64bd9ef4578c01ef964456 as it moved `brigand` directory to `include`.
Changing `-I<path-to-brigand>` to `-I<path-to-brigand>/include` or something along these lines should be enough, no?

**Comment by mkurdej** [comment]
PR https://github.com/ldionne/metabench/pull/172

**Comment by ldionne** [comment]
Thanks, that seems to fix it.
