### ISSUE TITLE
Moving to 80 Characters

### ISSUE THREAD

**Issue by nilsdeppe** [edouarda/brigand#247]
Looking at the Boost library guidelines they would like 80 character width. Any opposition to making this change in the ClangFormat file? It's probably easiest to at that point also shorten the headers and format the entire code base. I like what Louis has done for the file headers in hana. Do we want to steal this format?

**Comment by edouarda** [comment]
I'm not sure the 80 character width guideline makes any sense as people are not supposed to read the source code of Brigand, but fine (on a personal taste side, I don't mind 100+ lines).

What's specific about Louis' headers?

**Comment by nilsdeppe** [comment]
Yes, maybe the right answer is to change this as we go through the process of implementing what Kvasir uses (I personally use a setup where I can get three 80 wide beside each other on my monitor, but not 100 wide, but this is just personal anyway. two 100 wide is most certainly fine :) )

Sorry, yes that was a vague comment. I like what he's done with Doxygen, e.g.
```cpp
/*!
@file
Includes all the library components except the adapters for external
libraries.

@copyright Louis Dionne 2013-2017
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)
 */
```

**Comment by odinthenerd** [comment]
yeah fast tracks suck with 80 chars but its probably better to be uniform than anything else.

**Comment by edouarda** [comment]
The 80 chars limit is a "should", not a "must" and is a very old rule. I don't think there is a need to follow it and like @odinthenerd said it makes the TMP code a bit harder to read.

The headers à la Louis looks great, let's do that.

**Comment by nilsdeppe** [comment]
Alright sounds like a good plan then. I think readability will help maintainability anyway.

I'll start working on the headers over the next few days.

**Comment by edouarda** [comment]
Awesome, thanks!
