### ISSUE TITLE
include VERSION macros

### ISSUE THREAD

**Issue by nilsdeppe** [edouarda/brigand#256]
The version number, and ideally the current git hash would be kept inside a header. The canonical thing to do appears to be:

```cpp
#define BRIGAND_VERSION "1.3.2"
#define BRIGAND_VERSION_MAJOR 1
#define BRIGAND_VERSION_MINOR 3
#define BRIGAND_VERSION_BUGFIX 2
```

Should I add a header for this?

**Comment by edouarda** [comment]
That looks fine to me.
