### ISSUE TITLE
Minor Patch for logical and/or

### ISSUE THREAD

**Issue by Alexhuszagh** [edouarda/brigand#258]
On MSVC, with /W3 or higher (for warning C4800) issues a warning for my pull request to support [variadic and/or](https://github.com/edouarda/brigand/pull/252). The fix is quite simple: Change `bool(sizeof...(Ts) / 9)` to `(sizeof...(Ts) / 9) != 0` in all locations. This really have minimal repercussions otherwise, and I can submit a PR if these changes are desirable.

**Comment by edouarda** [comment]
Thank you, your TR is welcomed!
