### ISSUE TITLE
Duplicate in map.

### ISSUE THREAD

**Issue by Jarod42** [edouarda/brigand#26]
Duplicates in map key are only handled within the fastlane.

so

    using big_map = brigand::map<
        brigand::pair<type_one, int>,
        brigand::pair<type_two, type_one>,
        brigand::pair<type_three, type_two>,
        brigand::pair<type_four, type_three>,
        brigand::pair<type_five, type_four>,
        brigand::pair<type_six, type_five>,
        brigand::pair<type_seven, type_six>,
        brigand::pair<type_eight, type_seven>,
        brigand::pair<type_one, type_eight> // Duplicate
     >;

is a valid type whereas if we remove `brigand::pair<type_eight, type_seven>,`, we correctly have compile error.

**Comment by edouarda** [comment]
Oh yes, you are correct. I think a fix would be to carry the previously resolved types in a map at each recursive map and static_assert if it is resolved. What do you think Professeur @jfalcou ?

**Comment by edouarda** [comment]
@jfalcou I did something in branch issue26, the problem is that VS will not do anything at declaration, you somehow need to use the type for the static_assert to be triggered :x
