### ISSUE TITLE
Cannot compile structure with comma operator overload

### ISSUE THREAD

**Issue by edouarda** [edouarda/brigand#28]
brigand/algorithms/for_each.hpp(17): error C2062: type 'evil' unexp

And of course if I try to write Elements{}... I get internal compiler error :o

**Comment by jfalcou** [comment]
MSVC right ?

**Comment by edouarda** [comment]
Da

**Comment by Jarod42** [comment]
In fact, I think that `for_each` interface is wrong: The functor should implement `operator(T)` which is wrong.

But I don't know which interface is correct:
- `template <typename T> void operator ()()` may be difficult to (partially) specialize.
- `template <typename T> void operator () (Type<T>)` may look strange.
- `template <typename T> struct F { void operator()(); };` may look strange too.

**Comment by jfalcou** [comment]
I replicated the old MPL interface. Now I am open to change it.

- `template <typename T> void operator ()()` is indeed too complex to specialize
- `template <typename T> void operator () (Type<T>)` is OK if properly documented
- `template <typename T> struct F { void operator()(); };` is not equivalent to a lambda

I'm in favor of version 2.

**Comment by edouarda** [comment]
I think version 2 is the only viable option. I guess you mean Type<T> is a box?

**Comment by jfalcou** [comment]
the Type box yes. I'ma bout to push this fix.

**Comment by Jarod42** [comment]
Yes `Type<T>` is a box
