### ISSUE TITLE
add brigand::for_each

### ISSUE THREAD

**Issue by edouarda** [edouarda/brigand#3]

**Comment by jfalcou** [comment]
temptative implementation here : 
https://github.com/edouarda/brigand/commit/2f87ed733c7f5e2cf8456166bae8112bf0d1ce24

**Comment by jfalcou** [comment]
note that's an exact reimpelmentation of MPL for_each function. If a for_each metafunction is needed, we may need another implementation.

**Comment by edouarda** [comment]
Je testerai demain sous vs

--

Edouard ALLIGAND
Chairman & Chief Technical Officer
quasardb | 24 rue Feydeau | F-75002 Paris
tel : +33 1 55 34 92 30 | fax : +33 1 55 34 92 39
www.quasardb.net<http://www.quasardb.net/>

**Comment by jfalcou** [comment]
Works on my MSVC version, waiting for you to close this one.
