### ISSUE TITLE
Reduce the need to type ::type

### ISSUE THREAD

**Issue by edouarda** [edouarda/brigand#30]
I like the repetition in this issue ::issue

**Comment by jfalcou** [comment]
I removed the ::type from reverse. Don't think there's more

**Comment by edouarda** [comment]
I think you underestimate my ability to be 0ld SK00l

**Comment by jfalcou** [comment]
removed ::type from lookup

**Comment by edouarda** [comment]
I think there is none left?

**Comment by jfalcou** [comment]
unless you add more :p

**Comment by jfalcou** [comment]
closing for now
