### ISSUE TITLE
key `void` not supported in map

### ISSUE THREAD

**Issue by Jarod42** [edouarda/brigand#31]
`void` and other non default constructible type cannot be key of map:

changing in map.hpp

    template <typename T>
    struct Type {};

    // fastlane for constant amortized time
    template <class T0>
    struct map_impl<T0>
    {
        static typename T0::second_type at(Type<typename T0::first_type>);

        template <typename U>
        static no_such_type_ at(U) {}
    };

    // .. other fastlane

    template <typename M, typename K>
    struct lookup
    {
        using type = decltype(M::at(std::declval<Type<K>>())); // or using type = std::result_of_t<M::at(Type<K>)>;
    };

and in at.hpp

    template <typename T>
    struct has_at_method
    {
        struct dummy {};
        template <typename C, typename P>
        static auto test(P*) -> decltype(static_cast<void>(C::at(std::declval<Type<P>>())) /*cast to handle comma operator */, std::true_type());
        
        // previous false case + bool value
    };

solves that.

**Comment by jfalcou** [comment]
this type_ boxing seems to be rampant. I suggest making it a detail/type.hpp and fix it this way

**Comment by edouarda** [comment]
I agree.
