### ISSUE TITLE
brigand set

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#33]
shoudl support insert remove contains

idea is to have simialr thing than map but with a contains static member that return true_ if the key match

**Comment by jfalcou** [comment]
insert/remove remains

**Comment by edouarda** [comment]
ok I will do it for map/set

**Comment by jonathanpoelen** [comment]
What's your progression?

**Comment by edouarda** [comment]
Haven't started yet :)

**Comment by edouarda** [comment]
I will find some time today.

**Comment by edouarda** [comment]
Or tomorrow. :-)

**Comment by edouarda** [comment]
I had a look at what you did. I think it's too clever for VS. One alternative would be to have a recursive approach to insert/erase.

**Comment by edouarda** [comment]
Wait I found a way. :-)

**Comment by edouarda** [comment]
MMm VS doesn't like the unary_bind

**Comment by edouarda** [comment]
Check branch issue33 I have something that works on Win Win
