### ISSUE TITLE
add a unique<T...> metafunction

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#35]
unique<T...> return true_ if all T... are different

**Comment by edouarda** [comment]
How do you implement it? Build a set and then return false if you find any member?

**Comment by jfalcou** [comment]
no as if you make set<T,T> it will fails at compile time. I'm trying to see if we can live with the obvious O(N2) implementation or if it's again a dependent of sort

**Comment by edouarda** [comment]
With sort, it is trivial, if you have two consecutive identical items, then return true_type

**Comment by edouarda** [comment]
I mean false_type

**Comment by jonathanpoelen** [comment]
I tried something with std::integer_sequence (e4a3be2c12). I think to do without later.

is_unique seems better to me ...?

**Comment by edouarda** [comment]
Well, std::unique returns a sequence with only unique types, but it is not is_unique, rather something like is_set ?

**Comment by jonathanpoelen** [comment]
Ok for me.

**Comment by jfalcou** [comment]
clsoing this as it is follwoed by the latest issue on is_set
