### ISSUE TITLE
[Discussion] Should brigand also embeds small scale Fusion types & algorithms ?

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#36]
as in the title, should we have small scale, easy to grok and not compile-time heavy equivalent of fusion::vector and fusion::<some_algo> or are we diverging ?

**Comment by edouarda** [comment]
Let's do that in a second iteration. I would like to wrap up everything and have a decent doc. Then I'll blog about this library to promote it a bit more.

**Comment by jfalcou** [comment]
Perfect

**Comment by edouarda** [comment]
Do you think we should have a basic variant?

**Comment by jfalcou** [comment]
I hesitate because : 
 - people may want different variant with different tradeoffs. Look at the std::bikeshedding
- it starts to stretch the library. tuple are still TMP related. variant are subproducts.
- I dunno how to write an efficient one that dont look like ass

**Comment by edouarda** [comment]
I was thinking the variant should be in a separate library. For example "Raclure". :D

**Comment by edouarda** [comment]
I agree it shouldn't be part of Brigand.

**Comment by jfalcou** [comment]
We agree then. Let's close this and see what we can do later.
