### ISSUE TITLE
last_element improvement

### ISSUE THREAD

**Issue by Jarod42** [edouarda/brigand#37]
It can be rewritten as

    template <class... Ts>
    using last_element = decltype(type_<Ts>...)::type;

Maybe add a layer for a better message for 0-size.

**Comment by jfalcou** [comment]
As far as the standard is concerned alas, decltype() is not a proper context for pack expansion. clang, gcc and MSVC rejects this line alas :{

See coliru for ex:

http://coliru.stacked-crooked.com/a/e5255ab454a035bd

**Comment by Jarod42** [comment]
sorry for broken report.

**Comment by jfalcou** [comment]
I can tell you I wished it worked :€
