### ISSUE TITLE
warnings under gcc

### ISSUE THREAD

**Issue by Jarod42** [edouarda/brigand#38]
lot of warning for no return statement in map.hpp (whereas definition is not needed)

> brigand/sequences/map.hpp:20:37: warning: no return statement in function returning non-void [-Wreturn-type]
> static no_such_type_ at(U) {}

just replace by

     static no_such_type_ at(U);

> brigand/algorithms/for_each_args.hpp:15:82: warning: use of old-style cast [-Wold-style-cast]
> return (void)std::initializer_list<int>{(static_cast<void>(std::ref(f)((Ts&&)a)),0)...}, f;

Replace by `std::forward<Ts>(a)` (or by `static_cast<Ts&&>(a)`).

**Comment by jfalcou** [comment]
Closed in 14f74d454046d58e484699cd0ffc826b1dcfcff0
