### ISSUE TITLE
How to write meta-function combiner

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#42]
Let's say i want to write compose<F,G> that gimme something akin to F<G<T>> when applied to T.
or the negation fo a meta-function ?

Looks to me the syntax is not clear (see nope in all implementation).

**Comment by edouarda** [comment]
I wrote a compose function once.

It is not difficult.

Are you looking for h = f o g?
________________________________
De : Joel Falcou<mailto:notifications@github.com>
Envoyé : ‎24/‎07/‎2015 20:18
À : edouarda/brigand<mailto:brigand@noreply.github.com>
Objet : [brigand] How to write meta-function combiner (#42)


Let's say i want to write compose that gimme something akin to F> when applied to T.
or the negation fo a meta-function ?

Looks to me the syntax is not clear (see nope in all implementation).

**Comment by jfalcou** [comment]
how do you write it so it looks like a no ::type metafunction ?

**Comment by edouarda** [comment]
Ah sheet you meant metafunction, I red too quickly. 

Would you need something like this?

template <typename F, typename G>
struct compose
{
    template <typename X>
    using type = f<g<x>>;
};

But without the type?

**Comment by edouarda** [comment]
```cpp

template <typename X, typename F, typename G>
using compose = apply<X, F, G>
```

**Comment by edouarda** [comment]
Or something like that Mr. White.

**Comment by jfalcou** [comment]
I tried : 

    template <template<class> class F, template<class> class F G>
    struct compose_impl
    {
        template <typename X>
        using type = f<g<x>>;
    };
    
     template <template<class> class F, template<class> class F G>
     using compose = typename compose_impl<F,G>::type;

but MSVC chokes on it.

**Comment by edouarda** [comment]
Well I don't understand what you're trying to do, how would you pass X?

This works

```cpp
template <template<class> class F, template<class> class G>
struct compose_impl
{    
    template <typename X>
    using type = F<G<X>>;
};

 template <template<class> class F, template<class> class G>
 using compose = typename compose_impl<F,G>;

 
 template <typename X>
 using untz = compose<brigand::not_, brigand::not_>::type<X>;

 static_assert(untz<brigand::true_>::value == true, "untz");
```

**Comment by jfalcou** [comment]
we want compose to return something akin to a template<class> class, hence passing X later.
If not we can't pass result of compose to our algorithm

**Comment by edouarda** [comment]
Yes, but the compiler needs to know it has to pass a X.

When you type this:

```cpp
 using compose = typename compose_impl<F,G>::type;
```

Visual Studio doesn't like that you don't give the X to type, it thinks the type is incomplete. My question, is it valid to give incomplete type in that context?

I thought you should at least mention a template parameter is required.

**Comment by jonathanpoelen** [comment]
I do not think it is possible to make an alias on a template. 
For cons, the user can give the template type as a parameter:

```c++
template <template<class> class F, template<class> class G>
struct compose
{
    template <typename X>
    using type = F<G<X>>;
};

template<class T> using to_bool = brigand::bool_< T::value >;

int main(){
  using namespace brigand;

  using rng_0_to_4 = integral_list<int, 1, 2, 3, 4>;
  find<rng_0_to_4, compose<to_bool, prev>::type>{} = integral_list<int, 2, 3, 4>{};
}
```

The problem is moved ... :D

**Comment by edouarda** [comment]
This is also my impression.

**Comment by jfalcou** [comment]
In fact, yes. By going the road of alias == metafunction, the burden for the user is low, so he/she can do it manually. Closing this.
