### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by edouarda** [edouarda/brigand#48]
Hey guys, you've been many to have contributed to brigand, if you'd like to be listed as a contributor let me know here.

**Comment by jonathanpoelen** [comment]
I'm Jonathan Poelen and also a contributor.

Thank you :)

**Comment by edouarda** [comment]
Done :-)

**Comment by Jarod42** [comment]
Joris Dauphin for my comment :-)

**Comment by edouarda** [comment]
I think  we have more contributors than that, don't we? :-)

**Comment by jfalcou** [comment]
They're shy :p

**Comment by jfalcou** [comment]
and @edouarda  take names from here :  https://github.com/edouarda/brigand/graphs/contributors

**Comment by edouarda** [comment]
Ладно
