### ISSUE TITLE
Should we rename brigand::set to brigand::unordered_set

### ISSUE THREAD

**Issue by edouarda** [edouarda/brigand#51]
It's a set, but there is no order, thus unordered_set. :)

**Comment by jfalcou** [comment]
well unordered_set is quite a mouthful and I think the ordered/unordered_set mostly hints at the runtime kind of implementation no ?

**Comment by edouarda** [comment]
Well, it's not just a hint, set and unordered_set have different behavior when you iterate over the items and how you search for them.

However I think you are right, as in the context of brigand it doesn't really matter and we should just mention in the documentation "items in a set are guaranteed to be unique, however the order in which items are stored is undefined".

**Comment by jfalcou** [comment]
Let's close this one then
