### ISSUE TITLE
remove<List, Pred>

### ISSUE THREAD

**Issue by jonathanpoelen** [edouarda/brigand#52]
Removes all elements satisfying specific criteria.

**Comment by edouarda** [comment]
What about remove_if and remove?

Or is it too stlesque?

**Comment by jfalcou** [comment]
if ok with remove_if, we already have find and find_if.

Beign STLesque is okish there.

**Comment by jonathanpoelen** [comment]
brigand::find takes a predicate, so I did the same to remove. This is why there are no remove_if.

**Comment by jfalcou** [comment]
Fine for me

**Comment by edouarda** [comment]
Ok then!
