### ISSUE TITLE
implement brigand::map

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#8]
... with amortized O(1) at implementation + fast-lane for < 10 types

**Comment by edouarda** [comment]
Done and done :)

**Comment by edouarda** [comment]
However I tried to do some clever brigand:at wrapping and for some reason I can't get the right type out of at_c

**Comment by jfalcou** [comment]
Closed by 96138ba77473c7cfae4fa717e8b5581369dd4668
