### ISSUE TITLE
Implements mpl views

### ISSUE THREAD

**Issue by jfalcou** [edouarda/brigand#90]
- [ ] filter_view
- [ ] iterator_range
- [ ] joint_view
- [ ] single_view
- [ ] transform_view
- [ ] zip_view

**Comment by jfalcou** [comment]
@edouarda want your input on the fact we need those.

**Comment by edouarda** [comment]
Not in this milestone.

**Comment by jfalcou** [comment]
I mean globally

**Comment by edouarda** [comment]
I don't think it makes a lot of sense TBH. Views are useful in the dynamic world, but in the MP world everything is already a view, isn't it?

**Comment by jfalcou** [comment]
it's also based on iterators and we don't have them. So ...

**Comment by edouarda** [comment]
...close
